config/routes.rb
PinkyStatus::Application.routes.draw do
  root 'events#index'

  resources :events, only: [:index, :create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
  before_create :infer_status
  validate :no_events_in_the_same_minute

  def self.most_recent
    order(['created_at desc']).first
  end

  def self.most_recent_status
    most_recent ? most_recent.status : nil
  end

  def self.next_status
    if most_recent_status
      most_recent_status == 'in' ? 'out' : 'in'
    end
  end

  def self.most_recent_outing_events
    most_recent_in = order(['created_at desc']).where(status: 'in').first
    most_recent_out = order(['created_at desc']).where("created_at < ?", most_recent_in.created_at).first
    [most_recent_out, most_recent_in]
  end

  def invert
    update_attribute(:status, (status == 'in' ? 'out' : 'in'))
  end

  private

  def infer_status
    self.status ||= self.class.next_status
  end

  def no_events_in_the_same_minute
    if self.class.where("created_at >= ?", Time.now - 1.minute).any?
      errors.add(:base, "looks like a dupliate event")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @events = Event.order(['created_at desc']).page(params[:page]).per(50)
    @latest = Event.most_recent
  end

  def create
    Event.create(event_params)
    redirect_to events_path
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path
  end

  private

  def event_params
    params[:event].permit(:source, :status) rescue {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    params[:admin].present? && params[:admin] == ENV["ADMIN_PASSWORD"]
  end

  def arrow(status)
    if status == "in"
      content_tag(:i, "", class: %w(icon icon-arrow-left))
    else
      content_tag(:i, "", class: %w(icon icon-arrow-right))
    end
  end
end

app/views/events/index.html.erb
<div class="row">
  <div class="span12">
    <div class="hero-unit">
      <h1><span>Pinky is <%= @latest.status %>!</span></h1>
      <p><span>Pinky has been <%= @latest.status %> for <%= time_ago_in_words @latest.created_at %>.</span></p>
    </div>
  </div>
</div>
<div class="row">
  <div class="span5 offset1">
    <p>Pinky's most recent jaunt was for <strong><%= distance_of_time_in_words(*Event.most_recent_outing_events.map(&:created_at)) %></strong>.</p>
  </div>
  <div class="span5">
    <table class="table pull-right">
      <thead>
        <tr>
          <th>Event</th>
          <th>Time</th>
          <th>Source</th>
          <% if admin? %>
            <th>Remove</th>
          <% end %>
        </tr>
      <tbody>
        <% @events.each do |event| %>
          <%= content_tag_for :tr, event, title: "Event #{event.id}" do %>
            <td><%= event.status %> <%= arrow(event.status) %></td>
            <td><%= event.created_at.to_s(:short) %></td>
            <td><%= event.source %></td>
            <% if admin? %>
              <td><%= link_to event_path(event), :rel => "nofollow", method: :delete do %><i class="icon icon-remove"></i><span class="admin-link">remove</span><% end %></td>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @events %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PinkyStatus</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>